# -*- coding: utf-8 -*-

appVersion = 'v4.8.0.0'
phoneVersion = u'小米2s'

caseList = {
    'HuiLifeResourceNicheCases'             : u'惠生活',
    'SquareResourceNicheCases'              : u'广场资源位',
    'MovieTicketCases'                      : u'电影',
    'SquareMovieCases'                      : u'广场电影逛',
    'PrivilegeCouponCases'                  : u'广场优惠',
    'FoodCases'                             : u'美食汇',
    'SquareFoodCases'                       : u'广场美食汇',
    'SquareQueueCases'                      : u'广场排队取号',
    'BrandFamousCatergoryCases'             : u'品牌街(大牌)',
    'BrandRecommendCatergoryCases'          : u'品牌街(推荐)',
    'SquareIndoorMapCases'                  : u'广场室内地图',
    'SplashScreenHomePageCases'             : u'闪屏首页',
    'SwitchCityCases'                       : u'城市切换',
    'MyfeifanMyParkingPaymentCases'         : u'我的停车缴费',
    'ParkingBindingsCatergoryCases'         : u'首页停车',
    'SquareParkingPaymentCases'             : u'广场停车',
    'FeiFanCardBillCases'                   : u'飞凡通账单',
    'FeiFanCardIntegralCases'               : u'飞凡通其他快捷入口',
    'LoginCases'                            : u'我的登录',
    'MembershipCardPackageCases'            : u'我的会员卡包',
    'MessageSettingsCases'                  : u'我的消息中心',
    'MyfeifanMyLikeCases'                   : u'我的喜欢',
    'MyfeifanMyQueueCases'                  : u'我的排队',
    'OneCardCases'                          : u'我的飞凡通',
    'PersonalInformationCases'              : u'我的个人信息',
    'SmallAmountPasswordLessPaymentCases'   : u'我的设置(小额免密设置)',
    'SquareMemberCases'                     : u'广场会员',
    'SquareSignOnCases'                     : u'签到',
    'UpdateLoginPasswordCases'              : u'我的设置(修改密码)',
    'DashboardSearchBrandCases'             : u'全城搜索(品牌)',
    'DashboardSearchGoodsCases'             : u'全城搜索(商品)',
    'DashboardSearchStoreCases'             : u'全城搜索(门店)',
    'HotWordSearchCases'                    : u'热词搜索',
    'SquareFindStoreSearchCases'            : u'广场找店',
    'SquareSearchCases'                     : u'广场搜索',
    'LefuPayCatergoryCases'                 : u'买单',
    'ShoppingCatergoryCases'                : u'名店优品',
    'SquareLefuPayCases'                    : u'广场买单',
    'SquareShoppingCases'                   : u'广场爱购物',
}